sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
  
install:
  - npm install lix -g
  - lix download
  - haxelib install travix

script:
  - haxelib run travix js
  - haxelib run travix js -lib tink_hxx

env:
  - secure: "PVd+JLR4uOjx1pFM88aOwDW+x1wTzt5Az+Z6RIhGII+z+CP8S7o9HFTWhmslOuEKv7zSXj6TQogKwAbucni3V7aVNgzn/UGDWb0/UH0RoAId4iiiprLhUI0QTLTj3abxrPhC1fZtT7V5yajKlNvythp2dqafo7GSpNRunUZ1FUhlUr3dy0NYeHEby50EhIuH8vRamoHQRWyUtOHHB7v5uazRBvAzarhiNad2ZX8DgfbEWSzm81WBfwQMQLOJk8f7dcoPOq5DsgdybMput5XQ4CQD0ZVZbUW5bLKTzPdGpM74BFpYHmkGemohseDzTjjDocuxQd66g9S03+/scsY3RO3K0RDBQLIoxf6Odb1q4hKVlA1WitKKbum58PylCcwDz5WyNmwVr61RlWyPCLcKpsByMWtAYlJ7NXcA/GPYdu1STIXmjMWLxQ8/fGKIJ03t2H1EDFZHdsB/S60H51hGOvc1zBC3TYtq2h2yDFs7Yqnv3jzWRsiVf57+L/jJEtK+GExtatzzoc4nu2ldso40PjDISW4AeiU7EB5pJrRTJjmZhANqdq+/RA2qdVnlollOAlHmTGPQ6VfbrbgiKq5dmMnQW/TQ7T9s/Az86gShcXVweHmo5WL3vMWqKdjqEQq7ok9dtSSRkFdQni52bPMWoqTGa4K+LlcLUGzX7X9HkF4="

after_success:
- haxelib run travix release
